#ifndef MOTOR_CONFIG_H
#define MOTOR_CONFIG_H

#include "driver/gpio.h"

// M1三相PWM
#define M1_PWM_U_GPIO GPIO_NUM_26
#define M1_PWM_V_GPIO GPIO_NUM_27
#define M1_PWM_W_GPIO GPIO_NUM_14

// M1的AS5600
#define M1_SENSOR_SDA_GPIO GPIO_NUM_21
#define M1_SENSOR_SCL_GPIO GPIO_NUM_19
#define M1_AS5600_ADDRESS 0x36

// MCPWM计数器每秒计数1000万次
#define M1_PWM_TIMER_RESOLUTION_HZ 10000000UL

/*
 * 三相PWM频率。MCPWM使用上下计数模式，因此一个完整PWM周期包含两个计数斜坡。
 */
#define M1_PWM_FREQUENCY_HZ 20000UL

// ESP-IDF的上下计数模式把period_ticks定义为完整周期，比较峰值为其一半。
#define M1_PWM_PERIOD_TICKS       \
	(M1_PWM_TIMER_RESOLUTION_HZ / \
	 M1_PWM_FREQUENCY_HZ)

// MCPWM上下计数模式的比较值范围是0到period_ticks/2。
#define M1_PWM_COMPARE_MAX_TICKS (M1_PWM_PERIOD_TICKS / 2UL)

// EG2133采用自举高侧供电，暂时避免0%和100%
#define M1_PWM_MIN_DUTY 0.05f
#define M1_PWM_MAX_DUTY 0.95f

#define M1_MOTOR_POLE_PAIRS 7
#define M1_ELECTRICAL_ZERO_OFFSET_RAD 4.61f

/*
 * 初始电机模型参数：由当前 12 V、约 0.2 A、高速运行数据反推得到，
 * 用于 dq 交叉耦合和反电势前馈；后续可用堵转/阶跃测试再精确辨识。
 */
#define M1_MOTOR_PHASE_RESISTANCE_OHM 0.0f
#define M1_MOTOR_INDUCTANCE_D_H 0.019f
#define M1_MOTOR_INDUCTANCE_Q_H 0.019f
#define M1_MOTOR_FLUX_LINKAGE_WB 0.00053f
// 电角度零点校准默认关闭，避免每次上电都给电机通电。
#define M1_ENABLE_ELECTRICAL_ZERO_CALIBRATION 1

#define M1_CURRENT_LOOP_PWM_PERIODS 4U
#define M1_ENABLE_SPEED_LOOP 0
#define M1_SPEED_REF_RAD_S 0.0f
#define M1_CURRENT_LOOP_TEST_ID_REF_A 0.0f
#define M1_CURRENT_LOOP_TEST_IQ_REF_A 0.20f
#define M1_CURRENT_REFERENCE_RAMP_A_PER_S 0.10f
#define M1_CURRENT_LOOP_ID_PI_KP 1.5f
#define M1_CURRENT_LOOP_ID_PI_KI 8.0f
#define M1_CURRENT_LOOP_IQ_PI_KP 1.5f
#define M1_CURRENT_LOOP_IQ_PI_KI 8.0f
#define M1_ENABLE_TIMING_LOG 0
#define M1_ENABLE_CURRENT_TRACE 0
#define M1_CURRENT_TRACE_INTERVAL_LOOPS 5000U
#define M1_SPEED_PI_KP 0.05f
#define M1_SPEED_PI_KI 0.5f
#define M1_SPEED_IQ_LIMIT_A 0.02f
#define M1_SPEED_FEEDBACK_SIGN 1.0f
#define M1_SPEED_LOOP_PERIOD_MS 10U

// 12V 母线、限流 0.15A～0.20A 时使用的低电压对齐占空比。
#define M1_ALIGNMENT_DUTY_U 0.60f
#define M1_ALIGNMENT_DUTY_V 0.40f
#define M1_ALIGNMENT_DUTY_W 0.40f

// 对齐保持时间和软件电流保护阈值。
#define M1_ALIGNMENT_TIME_MS 1000U
#define M1_ALIGNMENT_MAX_CURRENT_A 5.20f
#define M1_ALIGNMENT_MIN_CURRENT_A 0.05f

#endif // !MOTOR_CONFIG_H
